# ---------- Dockerfile ----------

# Base image with Python
FROM python:3.12-slim

# Install system dependencies for Node.js, CDK, and Python packages
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    unzip \
    git \
    graphviz \
    && apt-get clean

# Install Node.js 20 and npm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g aws-cdk@^2 \
    && npm cache clean --force

# Instalal cdk-dia
RUN npm install -g cdk-dia

# Install aws cli2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip" \
    && unzip /tmp/awscliv2.zip -d /tmp \
    && /tmp/aws/install \
    && rm -rf /tmp/awscliv2.zip /tmp/aws

# Set working directory
WORKDIR /workspace

# Copy Python dependencies
COPY requirements.txt /workspace/

# Install Python dependencies globally
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Mount the workspace
VOLUME ["/workspace"]

# Default entrypoint: interactive bash
CMD ["/bin/bash"]
